# Generated by Django 3.1.6 on 2022-01-31 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('marketing_analytics', 'Marketing Analytics'), ('sales_analytics', 'Sales Analytics'), ('engineering_analytics', 'Engineering Analytics'), ('web_analytics', 'Web Analytics')], max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productcategory')),
                ('product_name', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0)),
                ('slogan', models.TextField(blank=True, null=True)),
                ('category2', models.CharField(blank=True, choices=[('Marketing Analytics', 'Marketing Analytics'), ('Sales Analytics', 'Sales Analytics'), ('Engineering Analytics', 'Engineering Analytics'), ('Web Analytics', 'Web Analytics')], max_length=140, null=True)),
                ('category', models.ForeignKey(blank=True, default=products.models.Product.get_or_create_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='products.productcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('products.productcategory',),
        ),
    ]
