# Generated by Django 4.0.2 on 2022-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_alter_productcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Candy', 'Candy'), ('Cereal', 'Cereal')], default='Cereal', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, choices=[('Candy', 'Candy'), ('Cereal', 'Cereal')], max_length=140, null=True),
        ),
    ]
