# Generated by Django 4.0.2 on 2022-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Candy', 'Candy'), ('Cereal', 'Cereal')], max_length=140, null=True),
        ),
    ]
